### ISSUE TITLE
Error while running the docker file

### ISSUE THREAD

**Issue by abhik1368** [xchem/fragalysis-stack#16]
Hi,

I installed docker and executing sudo docker-compose up and it shows me errors ...

web_1        |   File "/rdkit/rdkit/Chem/__init__.py", line 26, in <module>
web_1        |     from rdkit.Chem.inchi import *
web_1        | ImportError: No module named inchi

Can you point out what is going on ?

**Comment by abradle** [comment]
Hi Abhik,

Awesome that you're interested.

Just so you know this is pretty experimental. We probably won't do a major release for 6 months at least. But please do use - and let me know any ideas!

The issue was to do with base image differences. I believe I just fixed that. Does it work now?

Try: git pull && docker-compose down && docker-compose up -d --build

Best wishes,

Anthony

**Comment by abhik1368** [comment]
Thanks for your reply. I am getting an rdkit error like this below . Is it possible to change source of rdkit install ? 

sudo docker-compose up -d --build
WARNING: Some services (db, graph, web) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Building web
Step 1/18 : FROM informaticsmatters/rdkit:21e49472ed96
ERROR: Service 'web' failed to build: manifest for informaticsmatters/rdkit:21e49472ed96 not found

Cheers,
Abhik

**Comment by abradle** [comment]
It's not RDKit - it's that the image isn't accesbile to you. 

I've tagged a new image and updated the Dockerfile. It should work for you now.

**Comment by ypevzner** [comment]
Hello, I am working with Abhik on the same project. Thank you the installation has worked now. One more thing I had to do was to set ALLOWED_HOSTS to my box's IP as in the default installation it is set to "test.diamond.ac.uk".
One question I have is where the entry point into the web front end of the fragalysis Django app. Which page/url should I navigate to? Anything in urls.py seems to require an argument or a request. There doesn't seem to be an index.html or anything like that.
Thank you.

**Comment by abradle** [comment]
Hi both,

The functionality on this is very minimal and focused entirely towards what
we’re trying to do.

Loader.py is the script that loads data into the database. That should be
fairly straightforward.

Look at protein structures http://your ip/viewer/display/?target_title=Your target name

This is liable to change and potentiallly not work. First formal release is
in ~6 months.

Best wishes,

Anthony
