### ISSUE TITLE
Fragalysis Stack (re)build error - existing directory /code..

### ISSUE THREAD

**Issue by duncanpeacock** [xchem/fragalysis-stack#51]
When building the fragalysis stack for the second and subsequent times an error in the Dockerfile becomes apparent.
It fails trying to run a mkdir command because the directory already exists.  

The following workaround around line 34 fixed the problem:
RUN mkdir **-p** ${APP_ROOT}/static

NB: Suggestion from Alan: While fixing this, add to the end of lines && \ to link all the run commands together for efficiency.

**Comment by alanbchristie** [comment]
This is no longer an issue, especially as the stack build process is (will be) significantly different for the XCA-based stack.
